import type { CSSProperties } from 'react'

export const editableRootStyle = {
  '--slot4-page-bg': '#f6e7cb',
  '--slot4-page-text': '#2d0d09',
  '--slot4-panel-bg': '#fff2dc',
  '--slot4-surface-bg': '#fff8ee',
  '--slot4-muted-text': '#7a5648',
  '--slot4-soft-muted-text': '#9b7767',
  '--slot4-accent': '#9b0f06',
  '--slot4-accent-fill': '#d53e0f',
  '--slot4-accent-soft': '#f6c9b2',
  '--slot4-on-accent': '#fff8ef',
  '--slot4-dark-bg': '#250705',
  '--slot4-dark-text': '#f8ebd3',
  '--slot4-media-bg': '#e8d5b6',
  '--slot4-cream': '#eed9b9',
  '--slot4-warm': '#f2dfc1',
  '--slot4-lavender': '#f6e7cb',
  '--slot4-gray': '#efe2cd',
  '--slot4-body-gradient': 'radial-gradient(circle at top left, rgba(213,62,15,0.08), transparent 34%), linear-gradient(180deg, #f6e7cb 0%, #fff8ee 52%, #f2dfc1 100%)',
  '--editable-page-bg': '#f6e7cb',
  '--editable-page-text': '#2d0d09',
  '--editable-container': '1440px',
  '--editable-border': 'rgba(94,0,6,0.14)',
  '--editable-nav-bg': 'rgba(255,248,238,0.88)',
  '--editable-nav-text': '#2d0d09',
  '--editable-nav-active': '#9b0f06',
  '--editable-nav-active-text': '#fff8ef',
  '--editable-cta-bg': '#9b0f06',
  '--editable-cta-text': '#fff8ef',
  '--editable-search-bg': '#fff8ee',
  '--editable-footer-bg': '#250705',
  '--editable-footer-text': '#f8ebd3',
} as CSSProperties

export const editablePalette = {
  pageBg: 'bg-[var(--slot4-page-bg)]',
  pageText: 'text-[var(--slot4-page-text)]',
  panelBg: 'bg-[var(--slot4-panel-bg)]',
  panelText: 'text-[var(--slot4-page-text)]',
  surfaceBg: 'bg-[var(--slot4-surface-bg)]',
  surfaceText: 'text-[var(--slot4-page-text)]',
  mutedText: 'text-[var(--slot4-muted-text)]',
  softMutedText: 'text-[var(--slot4-soft-muted-text)]',
  accentText: 'text-[var(--slot4-accent)]',
  accentBg: 'bg-[var(--slot4-accent-fill)]',
  accentSoftBg: 'bg-[var(--slot4-accent-soft)]',
  accentSoftText: 'text-[var(--slot4-accent-soft)]',
  onAccentText: 'text-[var(--slot4-on-accent)]',
  darkBg: 'bg-[var(--slot4-dark-bg)]',
  darkText: 'text-[var(--slot4-dark-text)]',
  mediaBg: 'bg-[var(--slot4-media-bg)]',
  creamBg: 'bg-[var(--slot4-cream)]',
  warmBg: 'bg-[var(--slot4-warm)]',
  lavenderBg: 'bg-[var(--slot4-lavender)]',
  grayBg: 'bg-[var(--slot4-gray)]',
  border: 'border-[var(--editable-border)]',
  darkBorder: 'border-[rgba(238,217,185,0.16)]',
  shadow: 'shadow-[0_22px_50px_rgba(94,0,6,0.08)]',
  shadowStrong: 'shadow-[0_28px_80px_rgba(37,7,5,0.22)]',
  overlay: 'bg-[linear-gradient(180deg,rgba(37,7,5,0.02),rgba(37,7,5,0.84))]',
} as const

export const editableDesignContract = {
  shell: {
    page: `min-h-screen ${editablePalette.pageBg} ${editablePalette.pageText}`,
    section: 'mx-auto w-full max-w-[var(--editable-container)] px-4 sm:px-6 lg:px-8',
    sectionY: 'py-14 sm:py-16 lg:py-20',
  },
  layout: {
    safeGrid: 'grid gap-6 md:grid-cols-2 xl:grid-cols-3',
    featureGrid: 'grid gap-10 lg:grid-cols-[1.05fr_0.95fr] lg:items-start',
    rail: 'flex snap-x gap-5 overflow-x-auto pb-4 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden',
    minRailCard: 'w-[220px] shrink-0 snap-start sm:w-[240px]',
  },
  type: {
    eyebrow: 'text-[11px] font-semibold uppercase tracking-[0.28em] text-[var(--slot4-accent)]',
    heroTitle: 'text-4xl font-semibold leading-[0.95] tracking-[-0.07em] sm:text-5xl lg:text-7xl',
    sectionTitle: 'text-3xl font-semibold tracking-[-0.05em] sm:text-4xl lg:text-5xl',
    body: 'text-base leading-8',
  },
  surface: {
    card: `rounded-[1.5rem] border ${editablePalette.border} ${editablePalette.surfaceBg} ${editablePalette.shadow}`,
    soft: `rounded-[1.5rem] border ${editablePalette.border} ${editablePalette.panelBg}`,
    dark: `rounded-[1.5rem] ${editablePalette.darkBg} ${editablePalette.darkText} ${editablePalette.shadowStrong}`,
  },
  button: {
    primary: `inline-flex items-center justify-center gap-2 rounded-full bg-[var(--slot4-accent-fill)] px-6 py-3 text-sm font-semibold uppercase tracking-[0.14em] text-[var(--slot4-on-accent)] transition duration-300 hover:-translate-y-0.5 hover:brightness-95`,
    secondary: `inline-flex items-center justify-center gap-2 rounded-full border border-[var(--editable-border)] bg-[var(--slot4-surface-bg)] px-6 py-3 text-sm font-semibold uppercase tracking-[0.14em] text-[var(--slot4-page-text)] transition duration-300 hover:border-[var(--slot4-accent)] hover:text-[var(--slot4-accent)]`,
    accent: `inline-flex items-center justify-center gap-2 rounded-full bg-[var(--slot4-accent)] px-6 py-3 text-sm font-semibold uppercase tracking-[0.14em] text-[var(--slot4-on-accent)] transition duration-300 hover:-translate-y-0.5 hover:brightness-95`,
  },
  media: {
    frame: `relative overflow-hidden rounded-[1.25rem] ${editablePalette.mediaBg}`,
    ratio: 'aspect-[4/5]',
  },
  motion: {
    lift: 'transition duration-300 hover:-translate-y-1.5 hover:shadow-[0_20px_48px_rgba(94,0,6,0.14)] motion-reduce:transform-none',
    fade: 'transition duration-300 hover:opacity-85',
  },
} as const

export const aiLayoutRules = [
  'Keep the experience image-led and profile-aware; those are the enabled lanes.',
  'Use framed cards, poster-like headings, and warm industrial color contrast instead of generic SaaS layouts.',
  'Keep dynamic fetching intact and route all post links through the correct task routes.',
  'Support mobile deliberately with stacked layouts, capped line lengths, and no horizontal overflow.',
  'Make search, comments, pagination, and chips feel like part of the same visual system.',
] as const
